/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeIndexRouteImport } from './routes/trade/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as TradeTradeIdIndexRouteImport } from './routes/trade/$tradeId/index'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project/$projectId/index'
import { Route as TradeTradeIdReviewRouteImport } from './routes/trade/$tradeId/review'
import { Route as TradeTradeIdQuotesRouteImport } from './routes/trade/$tradeId/quotes'
import { Route as ProjectProjectIdReviewRouteImport } from './routes/project/$projectId/review'
import { Route as ProjectProjectIdQuotesRouteImport } from './routes/project/$projectId/quotes'
import { Route as TradeTradeIdVendorVendorIdRouteImport } from './routes/trade/$tradeId/vendor/$vendorId'

const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIndexRoute = TradeIndexRouteImport.update({
  id: '/trade/',
  path: '/trade/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/project/',
  path: '/project/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTradeIdIndexRoute = TradeTradeIdIndexRouteImport.update({
  id: '/trade/$tradeId/',
  path: '/trade/$tradeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/project/$projectId/',
  path: '/project/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTradeIdReviewRoute = TradeTradeIdReviewRouteImport.update({
  id: '/trade/$tradeId/review',
  path: '/trade/$tradeId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTradeIdQuotesRoute = TradeTradeIdQuotesRouteImport.update({
  id: '/trade/$tradeId/quotes',
  path: '/trade/$tradeId/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdReviewRoute = ProjectProjectIdReviewRouteImport.update({
  id: '/project/$projectId/review',
  path: '/project/$projectId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdQuotesRoute = ProjectProjectIdQuotesRouteImport.update({
  id: '/project/$projectId/quotes',
  path: '/project/$projectId/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTradeIdVendorVendorIdRoute =
  TradeTradeIdVendorVendorIdRouteImport.update({
    id: '/trade/$tradeId/vendor/$vendorId',
    path: '/trade/$tradeId/vendor/$vendorId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/project/': typeof ProjectIndexRoute
  '/trade/': typeof TradeIndexRoute
  '/project/$projectId/quotes': typeof ProjectProjectIdQuotesRoute
  '/project/$projectId/review': typeof ProjectProjectIdReviewRoute
  '/trade/$tradeId/quotes': typeof TradeTradeIdQuotesRoute
  '/trade/$tradeId/review': typeof TradeTradeIdReviewRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/trade/$tradeId/': typeof TradeTradeIdIndexRoute
  '/trade/$tradeId/vendor/$vendorId': typeof TradeTradeIdVendorVendorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/project': typeof ProjectIndexRoute
  '/trade': typeof TradeIndexRoute
  '/project/$projectId/quotes': typeof ProjectProjectIdQuotesRoute
  '/project/$projectId/review': typeof ProjectProjectIdReviewRoute
  '/trade/$tradeId/quotes': typeof TradeTradeIdQuotesRoute
  '/trade/$tradeId/review': typeof TradeTradeIdReviewRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/trade/$tradeId': typeof TradeTradeIdIndexRoute
  '/trade/$tradeId/vendor/$vendorId': typeof TradeTradeIdVendorVendorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/project/': typeof ProjectIndexRoute
  '/trade/': typeof TradeIndexRoute
  '/project/$projectId/quotes': typeof ProjectProjectIdQuotesRoute
  '/project/$projectId/review': typeof ProjectProjectIdReviewRoute
  '/trade/$tradeId/quotes': typeof TradeTradeIdQuotesRoute
  '/trade/$tradeId/review': typeof TradeTradeIdReviewRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/trade/$tradeId/': typeof TradeTradeIdIndexRoute
  '/trade/$tradeId/vendor/$vendorId': typeof TradeTradeIdVendorVendorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/project/'
    | '/trade/'
    | '/project/$projectId/quotes'
    | '/project/$projectId/review'
    | '/trade/$tradeId/quotes'
    | '/trade/$tradeId/review'
    | '/project/$projectId/'
    | '/trade/$tradeId/'
    | '/trade/$tradeId/vendor/$vendorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/project'
    | '/trade'
    | '/project/$projectId/quotes'
    | '/project/$projectId/review'
    | '/trade/$tradeId/quotes'
    | '/trade/$tradeId/review'
    | '/project/$projectId'
    | '/trade/$tradeId'
    | '/trade/$tradeId/vendor/$vendorId'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/project/'
    | '/trade/'
    | '/project/$projectId/quotes'
    | '/project/$projectId/review'
    | '/trade/$tradeId/quotes'
    | '/trade/$tradeId/review'
    | '/project/$projectId/'
    | '/trade/$tradeId/'
    | '/trade/$tradeId/vendor/$vendorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
  TradeIndexRoute: typeof TradeIndexRoute
  ProjectProjectIdQuotesRoute: typeof ProjectProjectIdQuotesRoute
  ProjectProjectIdReviewRoute: typeof ProjectProjectIdReviewRoute
  TradeTradeIdQuotesRoute: typeof TradeTradeIdQuotesRoute
  TradeTradeIdReviewRoute: typeof TradeTradeIdReviewRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  TradeTradeIdIndexRoute: typeof TradeTradeIdIndexRoute
  TradeTradeIdVendorVendorIdRoute: typeof TradeTradeIdVendorVendorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/': {
      id: '/trade/'
      path: '/trade'
      fullPath: '/trade/'
      preLoaderRoute: typeof TradeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/project'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$tradeId/': {
      id: '/trade/$tradeId/'
      path: '/trade/$tradeId'
      fullPath: '/trade/$tradeId/'
      preLoaderRoute: typeof TradeTradeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$tradeId/review': {
      id: '/trade/$tradeId/review'
      path: '/trade/$tradeId/review'
      fullPath: '/trade/$tradeId/review'
      preLoaderRoute: typeof TradeTradeIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$tradeId/quotes': {
      id: '/trade/$tradeId/quotes'
      path: '/trade/$tradeId/quotes'
      fullPath: '/trade/$tradeId/quotes'
      preLoaderRoute: typeof TradeTradeIdQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/review': {
      id: '/project/$projectId/review'
      path: '/project/$projectId/review'
      fullPath: '/project/$projectId/review'
      preLoaderRoute: typeof ProjectProjectIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/quotes': {
      id: '/project/$projectId/quotes'
      path: '/project/$projectId/quotes'
      fullPath: '/project/$projectId/quotes'
      preLoaderRoute: typeof ProjectProjectIdQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$tradeId/vendor/$vendorId': {
      id: '/trade/$tradeId/vendor/$vendorId'
      path: '/trade/$tradeId/vendor/$vendorId'
      fullPath: '/trade/$tradeId/vendor/$vendorId'
      preLoaderRoute: typeof TradeTradeIdVendorVendorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  ProjectIndexRoute: ProjectIndexRoute,
  TradeIndexRoute: TradeIndexRoute,
  ProjectProjectIdQuotesRoute: ProjectProjectIdQuotesRoute,
  ProjectProjectIdReviewRoute: ProjectProjectIdReviewRoute,
  TradeTradeIdQuotesRoute: TradeTradeIdQuotesRoute,
  TradeTradeIdReviewRoute: TradeTradeIdReviewRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  TradeTradeIdIndexRoute: TradeTradeIdIndexRoute,
  TradeTradeIdVendorVendorIdRoute: TradeTradeIdVendorVendorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
