/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeIndexRouteImport } from './routes/trade/index'
import { Route as TradeTradeIdRouteImport } from './routes/trade/$tradeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIndexRoute = TradeIndexRouteImport.update({
  id: '/trade/',
  path: '/trade/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTradeIdRoute = TradeTradeIdRouteImport.update({
  id: '/trade/$tradeId',
  path: '/trade/$tradeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/trade/$tradeId': typeof TradeTradeIdRoute
  '/trade/': typeof TradeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/trade/$tradeId': typeof TradeTradeIdRoute
  '/trade': typeof TradeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/trade/$tradeId': typeof TradeTradeIdRoute
  '/trade/': typeof TradeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/trade/$tradeId' | '/trade/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/trade/$tradeId' | '/trade'
  id: '__root__' | '/' | '/trade/$tradeId' | '/trade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TradeTradeIdRoute: typeof TradeTradeIdRoute
  TradeIndexRoute: typeof TradeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/': {
      id: '/trade/'
      path: '/trade'
      fullPath: '/trade/'
      preLoaderRoute: typeof TradeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/$tradeId': {
      id: '/trade/$tradeId'
      path: '/trade/$tradeId'
      fullPath: '/trade/$tradeId'
      preLoaderRoute: typeof TradeTradeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TradeTradeIdRoute: TradeTradeIdRoute,
  TradeIndexRoute: TradeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
